### ISSUE TITLE
Data page not showing

### ISSUE THREAD

**Issue by eigilevensen** [oisteinaa/upgraded-guacamole#5]
Data page is blank whereas rms- and map-pages work. Maybe need to fill up with more data before ready?

**Comment by eigilevensen** [comment]
Has worked every time before

**Comment by eigilevensen** [comment]
**Also the other pages died. Flask message:**

127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "GET /data/_dash-component-suites/plotly/package_data/plotly.min.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:30] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:31] "POST /maps/_dash-update-component HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/inst/.local/lib/python3.10/site-packages/dash/dash.py", line 1376, in dispatch
    ctx.run(
  File "/home/inst/.local/lib/python3.10/site-packages/dash/_callback.py", line 514, in add_context
    raise err
  File "/home/inst/.local/lib/python3.10/site-packages/dash/_callback.py", line 503, in add_context
    output_value = _invoke_callback(func, *func_args, **func_kwargs)
  File "/home/inst/.local/lib/python3.10/site-packages/dash/_callback.py", line 43, in _invoke_callback
    return func(*args, **kwargs)  # %% callback invoked %%
  File "/home/inst/upgraded-guacamole/src/Mapui/map_plot.py", line 62, in update_graph_live
    gdf = gpd.GeoDataFrame(rmsdf, geometry=geom, crs="EPSG:32633")
  File "/usr/lib/python3/dist-packages/geopandas/geodataframe.py", line 184, in __init__
    self.set_geometry(geometry, inplace=True)
  File "/usr/lib/python3/dist-packages/geopandas/geodataframe.py", line 320, in set_geometry
    frame[geo_column_name] = level
  File "/usr/lib/python3/dist-packages/geopandas/geodataframe.py", line 1351, in __setitem__
    super().__setitem__(key, value)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 3612, in __setitem__
    self._set_item(key, value)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 3784, in _set_item
    value = self._sanitize_column(value)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 4509, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/usr/lib/python3/dist-packages/pandas/core/common.py", line 531, in require_length_match
    raise ValueError(
ValueError: Length of values (14874) does not match length of index (4276)
127.0.0.1 - - [19/Oct/2024 10:02:36] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:41] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:47] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:51] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:02:56] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:03:02] "POST /data/_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [19/Oct/2024 10:03:05] "GET /rms/ HTTP/1.1" 200 -

**Comment by oisteinaa** [comment]
We have hardcoded length of data at line 22:

geom = [ls.interpolate(distance) for distance in np.linspace(0, ls.length, 14874)]

We have to change this to use the shape key of the raw files

**Comment by oisteinaa** [comment]
Should work now, problem is when interval is too short and the next one is fired before previous is done

**Comment by oisteinaa** [comment]
Possible solution

import time
import datetime
import diskcache

from dash import Dash, DiskcacheManager, Input, Output, html, dcc, callback

# Diskcache for non-production apps when developing locally
cache = diskcache.Cache("./cache")
background_callback_manager = DiskcacheManager(cache)

app = Dash(
    __name__, 
    background_callback_manager=background_callback_manager, 
    suppress_callback_exceptions=True
)

app.layout = html.Div(
    [
        html.Div(
            id="paragraph_id", 
            children="background callback starts at app initiation"
        ),
        html.Div(id='interval_container'),
        html.Div(id='out')
    ]
)


@callback(
    output=[
        Output("paragraph_id", "children"),
        Output("interval_container", "children"),
    ],
    inputs=Input("interval_container", "style"),
    background=True,
)
def update_clicks(_):
    time.sleep(6.0)
    return [f"Background callback finished"], dcc.Interval(id='interval', interval=1 * 1000, n_intervals=0)


@app.callback(
    Output('out', 'children'),
    Input('interval', 'n_intervals')
)
def timestamp(_):
    return str(datetime.datetime.now())


if __name__ == "__main__":
    app.run(debug=True)

**Comment by oisteinaa** [comment]
Problem is that the data changes to 250 000 samples. Even though he number of channels reduces it becomes more raw data since we are limiting to 350 channels anyhow. The solution is to take the data out of the json and make a separate channel for raw data. Raw data can be binary and compressed to speed things up. 

I have disabled the raw data in the json now, so the seismic plot wont work until fixed in new issue
